# Generated by Django 6.0.3 on 2026-06-25 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0005_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategory_images/')),
                ('needed_for', models.CharField(blank=True, help_text='Describe who needs or who this subcategory is intended for.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='flipkart.category')),
            ],
            options={
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
