# Generated by Django 6.0.3 on 2026-06-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_owner_selected',
            field=models.BooleanField(default=False, help_text='Show this product in the home page owner-picked section.'),
        ),
    ]
