# Generated by Django 6.0.3 on 2026-06-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0010_product_is_owner_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_owner_selected',
            new_name='is_show_top_poduct',
        ),
    ]
