# Generated by Django 6.0.3 on 2026-06-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0011_rename_is_owner_selected_product_is_show_top_poduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_show_top_poduct',
            new_name='is_owner_selected',
        ),
    ]
