# Generated by Django 6.0.3 on 2026-06-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0009_cart'),
        ('flipkart', '0012_rename_is_show_top_poduct_product_is_owner_selected'),
    ]

    operations = [
    ]
