# Generated by Django 6.0.3 on 2026-06-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0013_merge_20260630_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='not_show',
            field=models.BooleanField(default=False),
        ),
    ]
