# Generated by Django 6.0.3 on 2026-07-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0015_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100, null=True, unique=True),
        ),
    ]
